# Generated by Django 5.1.4 on 2025-01-01 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("home", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="interaction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interactions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="kyc",
            name="assignee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="kycs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="kyc",
            name="certified_statuses",
            field=models.ManyToManyField(
                blank=True, related_name="kyc_certified_statuses", to="home.file"
            ),
        ),
        migrations.AddField(
            model_name="kyc",
            name="kbis",
            field=models.ManyToManyField(
                blank=True, related_name="kyc_kbis", to="home.file"
            ),
        ),
        migrations.AddField(
            model_name="kyc",
            name="tax_returns",
            field=models.ManyToManyField(
                blank=True, related_name="kyc_tax_returns", to="home.file"
            ),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="contact",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="opportunities",
                to="home.contact",
            ),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="file",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="opportunities",
                to="home.file",
            ),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="opportunities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="billing",
            name="opportunity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="billings",
                to="home.opportunity",
            ),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="opportunities",
                to="home.product",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="partner",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="home.partner",
            ),
        ),
        migrations.AddField(
            model_name="billing",
            name="partner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="billings",
                to="home.partner",
            ),
        ),
    ]
