from home.views.account import *
from home.views.billing import *
from home.views.client import *
from home.views.contact import *
from home.views.dashboard import *
from home.views.file import *
from home.views.health import *
from home.views.interaction import *
from home.views.kyc import *
from home.views.opportunity import *
from home.views.partner import *
from home.views.product import *
