from home.serializers.account import *
from home.serializers.billing import *
from home.serializers.client import *
from home.serializers.contact import *
from home.serializers.dashboard import *
from home.serializers.file import *
from home.serializers.interaction import *
from home.serializers.kyc import *
from home.serializers.opportunity import *
from home.serializers.partner import *
from home.serializers.product import *
